spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_db
    username: postgres
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.type.mapping: event:events.order.OrderCreatedEvent
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081